config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'session/login'
  get 'session/logout'
  post 'session/create'
  resources :recipes
  resources :users
  get 'cook_book/main_page'
  root to: 'cook_book#main_page'

  get '/:locale' => 'cook_book#main_page'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  include ActiveModel::Validations
  self.abstract_class = true
end

app/models/recipe.rb
# frozen_string_literal: true

class Recipe < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates_format_of :name, without: /\d/
  validates :time, presence: true, numericality: { only_integer: true }, length: { maximum: 3 }
  validates :ingred, :descrip, presence: true
  validates_format_of :image, with: %r{(^\s*$)|(https:/)}
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_many :recipes

  has_secure_password

  validates :username, presence: true, uniqueness: true, length: { maximum: 20 }
  validates :f_name, presence: true, length: { maximum: 30 }
  validates :s_name, presence: true, length: { maximum: 30 }
  validates :email, presence: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :password, confirmation: true, length: { minimum: 3 }
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionHelper
  before_action :require_login
  around_action :switch_locale

  private

  def require_login
    unless signed_in?
      flash[:danger] = 'Требуется логин'
      redirect_to :session_login
    end
  end

  def switch_locale(&action)
    locale = params[:locale] || I18n.default_locale
    I18n.with_locale(locale, &action)
  end
end

app/controllers/cook_book_controller.rb
# frozen_string_literal: true

class CookBookController < ApplicationController
  skip_before_action :require_login, only: %i[main_page cook_page]

  def main_page
    @recipes = Recipe.all.map do |elem|
      { id: elem.id, name: elem.name, ingred: elem.ingred, level: elem.level, descrip: elem.descrip, image: elem.image,
        time: elem.time, username: User.find_by(id: elem.user_id).username }
    end.each_slice(2).map.to_a
  end
end

app/controllers/recipes_controller.rb
# frozen_string_literal: true

class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  skip_before_action :require_login, only: %i[show]

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show; end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(**recipe_params, user_id: current_user.id)
    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to user_url(current_user), notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :level, :ingred, :descrip, :time, :image)
  end
end

app/controllers/session_controller.rb
# frozen_string_literal: true

class SessionController < ApplicationController
  skip_before_action :require_login
  def login; end

  def logout
    sign_out
    redirect_to root_path
  end

  def create
    user = User.find_by(username: params[:username])

    if user&.authenticate(params[:password])
      p 'Login'
      sign_in user
      redirect_to root_path
      p signed_in?
    else
      p 'Redirected'
      flash.now[:danger] = 'Неверный логин или пароль'
      redirect_to session_login_path
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[show edit update destroy]
  skip_before_action :require_login

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
    @user_recipes = Recipe.where(user_id: @user.id).all.map do |elem|
      { id: elem.id, name: elem.name, ingred: elem.ingred, descrip: elem.descrip, image: elem.image, time: elem.time }
    end
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit; end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to user_url(@user), notice: 'User was successfully created.' }
        format.json { render root_path, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to user_url(@user), notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:f_name, :s_name, :username, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/cook_book_helper.rb
# frozen_string_literal: true

module CookBookHelper
end

app/helpers/recipes_helper.rb
# frozen_string_literal: true

module RecipesHelper
end

app/helpers/session_helper.rb
# frozen_string_literal: true

module SessionHelper
  def sign_in(user)
    cookies.signed[:user_id] = { value: user.id, expires: 1.hour }
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    cookies.signed[:user_id] = nil
    self.current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_id(cookies.signed[:user_id])
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/cook_book/main_page.html.erb
<div>
  <h3 style="margin: 20px"><%=t('page.cook_book') %></h3>
</div>
<div class="container-md">
  <% if @recipes.empty? %>
    <div><%=t('page.no_recipes') %></div>
  <% else %>
    <% @recipes.each do |pair_recipe| %>
        <div class="row row-cols-1 row-cols-md-2 g-4" style="margin-inline: 5% ">
        <% pair_recipe.each do |recipe| %>
        <div class="col">
          <div class="card mb-3">
            <div class="row g-0">
              <div class="col-md-4">
                <img src="<%=recipe[:image]%>" class="img-fluid rounded-start" alt="...">
              </div>
              <div class="col-md-8">
                <div class="card-body">
                  <a href="/recipes/<%=recipe[:id] %>"><h4><%=recipe[:name]%></h4></a>
                  <p class="card-text"><%= t('recipe.level') %>: <%=recipe[:level]%><br/>
                  <%= t('recipe.time') %>: <%= recipe[:time]%> мин</p>
                  <p class="card-text"><small class="text-muted"><%=t('user.author') %>: <%=recipe[:username] %></small></p>
                </div>
              </div>
            </div>
          </div>
        </div>
    <% end %>
    </div>
  <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CookBook</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body style="margin: 0">
<nav class="navbar navbar-light" style="background-color: #ffe3ed; margin-bottom: 20px">
  <div class="container-fluid">
    <a class="navbar-brand" style="color: #ff0081" href=<%= root_path %>><%=t('page.home')%></a>
    <% if !current_page?(session_login_path) && !current_page?(session_create_path) %>
      <% p signed_in? %>
      <% if !signed_in? %>
        <form class="d-flex">
          <a class="nav-link" style="color: #ff0081" href=<%= session_login_path %>><%=t('login')%></a>
          <a class="nav-link" style="color: #ff0081" href=<%= new_user_path %>><%=t('register')%></a>
        </form>
      <% else %>
        <form class="d-flex">
          <a class="nav-link" style="color: #ff0081" href="/users/<%=current_user.id%>"><%=t('page.my_page')%></a>
          <a class="nav-link" style="color: #ff0081" href=<%= new_recipe_path %> ><%=t('page.add_recipe')%></a>
          <a class="nav-link" style="color: #ff0081" href=<%=session_logout_path%> ><%=t('logout')%></a>
        </form>
      <% end %>
    <% end %>
  </div>
</nav>


<%= yield %>


<div class="footer d-flex flex-wrap justify-content-between align-items-center py-3 border-top" style="background-color: #ffe3ed; margin-top: 30px">
  <div class="col-md-4 d-flex align-items-center">
    <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
      <svg class="bi" width="30" height="24">
        <use xlink:href="#bootstrap"></use>
      </svg>
    </a>
    <span class="text-muted">© Yakovleva Varvara, IU6-35B</span>
  </div>
    <a class="text-muted" href="https://instagram.com/_varya_ya?utm_medium=copy_link" style="margin-right: 20px">
      <img class="bi" width="24" height="24" src="https://img.icons8.com/fluency/344/instagram-new.png" alt="..."/>
    </a>
  </ul>
</div>
</body>
</html>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.number_field :level %>
  </div>

  <div class="field">
    <%= form.label :ingred %>
    <%= form.text_area :ingred %>
  </div>

  <div class="field">
    <%= form.label :descrip %>
    <%= form.text_area :descrip %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.number_field :time %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/edit.html.erb
<div class="form-recipe">

  <% if @recipe.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <%= t('error.empty_gaps') %>
    </div>
  <% end %>

  <%= form_with(model: @recipe, local: true, class: "row g-3") do |form| %>
    <h1 class="h3 mb-3 fw-normal" style="margin-top: 50px"><%=t('page.edit_gaps') %></h1>

    <div class="row g-2">
      <div class="form-floating">
        <%= form.text_field :name, required: true, class: "form-control", :placeholder => t('recipe.name')%>
        <label for="floatingInput" style="margin-left: 10px"><%=t('recipe.name') %></label>
      </div>
    </div>
    <div class="row g-2">
      <h5><%=t('recipe.level') %></h5>
      <div class="col">
        <div class="form-check form-check-inline">
          <%= form.radio_button :level, 1, :checked => true, class: "form-check-input" %>
          <%= form.label :level, '1', class: "form-check-label", style: 'display: inline-block;' %>
        </div>
        <div class="form-check form-check-inline">
          <%= form.radio_button :level, 2, class: "form-check-input" %>
          <%= form.label :level, '2', class: "form-check-label" %>
        </div>
        <div class="form-check form-check-inline">
          <%= form.radio_button :level, 3, class: "form-check-input" %>
          <%= form.label :level, '3', class: "form-check-label" %>
        </div>
      </div>
    </div>
    <div class="row g-2">
      <div class="form-floating">
        <%= form.text_field :time, required: true, class: "form-control", :placeholder => t('recipe.time') %>
        <label for="floatingInput" style="margin-left: 10px"><%=t('recipe.time') %></label>
      </div>
    </div>

    <div class="row g-2">
      <div class="form-floating">
        <%= form.text_area :ingred, required: true, class: "form-control", :placeholder => t('recipe.ingred'), rows: 3 %>
        <label for="recipe_ingred" style="margin-left: 10px "><%=t('recipe.ingred') %></label>
      </div>
    </div>

    <div class="row g-2">
      <div class="form-floating">
        <%= form.text_area :descrip, required: true, class: "form-control", :placeholder => t('recipe.descrip'), rows: 5 %>
        <label for="recipe_descrip" style="margin-left: 10px "><%=t('recipe.descrip') %></label>
      </div>
    </div>

    <div class="row g-2">
      <div class="form-floating">
        <%= form.text_field :image, required: true, class: "form-control", :placeholder => t('recipe.url') %>
        <label for="floatingInput" style="margin-left: 10px"><%=t('recipe.url') %></label>
      </div>
    </div>

    <div class="col-1"></div>
    <div class="col-10">
      <%= form.submit value: t('save'), class: "w-100 btn btn-primary" %>
    </div>
    <div class="col-1"></div>

  <% end %>
</div>

app/views/recipes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Recipes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Level</th>
      <th>Ingred</th>
      <th>Descrip</th>
      <th>Time</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recipes.each do |recipe| %>
      <tr>
        <td><%= recipe.name %></td>
        <td><%= recipe.level %></td>
        <td><%= recipe.ingred %></td>
        <td><%= recipe.descrip %></td>
        <td><%= recipe.time %></td>
        <td><%= recipe.image %></td>
        <td><%= link_to 'Show', recipe %></td>
        <td><%= link_to 'Edit', edit_recipe_path(recipe) %></td>
        <td><%= link_to 'Destroy', recipe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recipe', new_recipe_path %>

app/views/recipes/new.html.erb
<div class="form-recipe">

  <% if @recipe.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <%= t('error.empty_gaps') %>
    </div>
  <% end %>


  <%= form_with(model: @recipe, local: true, class: "row g-3") do |form| %>

    <h1 class="h3 mb-3 fw-normal" style="margin-top: 50px"><%= t('page.fill_gaps') %></h1>

    <div class="row g-2">
      <div class="form-floating">
        <%= form.text_field :name, required: true, class: "form-control", :placeholder => t("name") %>
        <label for="floatingInput" style="margin-left: 10px"><%= t('recipe.name') %></label>
      </div>
    </div>
    <div class="row g-2">
      <h5><%= t('recipe.level') %></h5>
      <div class="col">
        <div class="form-check form-check-inline">
          <%= form.radio_button :level, 1, :checked => true, class: "form-check-input" %>
          <%= form.label :level, '1', class: "form-check-label", style: 'display: inline-block;' %>
        </div>
        <div class="form-check form-check-inline">
          <%= form.radio_button :level, 2, class: "form-check-input" %>
          <%= form.label :level, '2', class: "form-check-label" %>
        </div>
        <div class="form-check form-check-inline">
          <%= form.radio_button :level, 3, class: "form-check-input" %>
          <%= form.label :level, '3', class: "form-check-label" %>
        </div>
      </div>
    </div>
    <div class="row g-2">
      <div class="form-floating">
        <%= form.text_field :time, required: true, class: "form-control", :placeholder => t('recipe.time') %>
        <label for="floatingInput" style="margin-left: 10px"><%= t('recipe.time') %></label>
      </div>
    </div>

    <div class="row g-2">
      <div class="form-floating">
        <%= form.text_area :ingred, required: true, class: "form-control", :placeholder => t('recipe.ingred'), rows: 5 %>
        <label for="recipe_ingred" style="margin-left: 10px "><%= t('recipe.ingred') %></label>
      </div>
    </div>

    <div class="row g-2">
      <div class="form-floating">
        <%= form.text_area :descrip, required: true, class: "form-control", :placeholder => t('recipe.descrip'), rows: 7 %>
        <label for="recipe_descrip" style="margin-left: 10px "><%= t('recipe.descrip') %></label>
      </div>
    </div>

    <div class="row g-2">
      <div class="form-floating">
        <%= form.text_field :image, required: true, class: "form-control", :placeholder => t('recipe.url') %>
        <label for="floatingInput" style="margin-left: 10px"><%= t('recipe.url') %></label>
      </div>
    </div>

    <div class="col-1"></div>
    <div class="col-10" style="margin-bottom: 40px; margin-top: 20px">
      <%= form.submit value: t('page.add_recipe'), class: "w-100 btn btn-primary" %>
    </div>
    <div class="col-1"></div>

  <% end %>
</div>

app/views/recipes/show.html.erb
<div class="container">
  <div class="row" style="margin-bottom: 40px; margin-top: 40px">
    <div class="col-10"><h2><%= @recipe.name %></h2></div>
    <div class="col-2" style="align-content: center">
      <% if !@recipe.present? && @recipe.user_id == current_user.id %>
        <div class="btn-group" role="group" aria-label="Basic outlined example">
          <%= button_to(t('change'), edit_recipe_path(@recipe), method: :get, class: "btn btn-outline-secondary btn-sm") %>
          <%= button_to(t('delete'), @recipe, :method => "delete", data: true, class: "btn btn-outline-secondary btn-sm", style: "margin-left: 7px") %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="row justify-content-between" style="justify-content: center">
    <div class="col-4">
      <div>
        <img class="img-fluid rounded" src="<%= @recipe.image %>"
             style="margin-bottom: 40px">
      </div>
      <div style="margin-bottom: 10px">
        <h6><%= t('recipe.level') %>
          <% @recipe.level.times do %>
            <img src="https://img.icons8.com/material-sharp/24/000000/star--v1.png"/>
          <% end %></h6>
      </div>
      <div style="margin-bottom: 10px">
        <h6><%= t('recipe.time') %> :
          <img src="https://img.icons8.com/ios-glyphs/30/000000/timer.png"/><%= @recipe.time %> мин. </h6>
      </div>
    </div>
    <div class="col-1"></div>
    <div class="col-7">
      <div>
        <h5><%= t('recipe.ingred') %> </h5>
        <p><%= @recipe.ingred %></p>
      </div>

      <div>
        <h5><%= t('recipe.descrip') %></h5>
        <p><%= @recipe.descrip %></p>
      </div>
    </div>
  </div>
</div>

app/views/session/create.html.erb
<div class="form-signin">



  <form class="row g-3">
    <h1 class="h3 mb-3 fw-normal" style="margin-top: 50px"><%=t('page.fill_gaps') %></h1>

    <div class="row g-2">
      <div class="col">
        <div class="form-floating">
          <input type="text" class="form-control" id="floatingInput" placeholder="name">
          <label for="floatingInput" style="margin-left: 10px"><%=t('user.f_name') %></label>
        </div>
      </div>
      <div class="col">
        <div class="form-floating">
          <input type="text" class="form-control" id="floatingInput" placeholder="surname">
          <label for="floatingInput" style="margin-left: 10px"><%=t('user.s_name') %></label>
        </div>
      </div>
    </div>

    <div class="row g-2">
      <div class="form-floating">
        <input type="text" class="form-control" id="floatingInput" placeholder="username">
        <label for="floatingInput" style="margin-left: 10px"><%=t('user.username') %></label>
      </div>
    </div>

    <div class="row g-2">
      <div class="form-floating">
        <input type="email" class="form-control" id="floatingInput" placeholder="name@example.com">
        <label for="floatingInput" style="margin-left: 10px"><%=t('user.email') %></label>
      </div>
    </div>

    <div class="row g-2">
      <div class="col">
        <div class="form-floating">
          <input type="password" class="form-control" id="floatingInput" placeholder="password">
          <label for="floatingInput" style="margin-left: 10px"><%=t('user.password') %></label>
        </div>
      </div>
      <div class="col">
        <div class="form-floating">
          <input type="password" class="form-control" id="floatingInput" placeholder="password">
          <label for="floatingInput" style="margin-left: 10px"><%=t('user.conf_password') %></label>
        </div>
      </div>
    </div>

    <div class="col-1"></div>
    <div class="col-10">
      <button type="submit" class="w-100 btn btn-primary" style="margin-top: 20px"><%=t('register') %></button>
    </div>

    <div class="col-1"></div>
  </form>
</div>

app/views/session/login.html.erb
<div class="container form-signin align-content-center justify-content-center">
  <h1 class="h3 fw-normal" style="margin-top: 70px; margin-bottom: 50px"><%=t('page.fill_gaps') %></h1>
  <%= form_with url: session_create_url, method: :post, local: true,class:'row g-3 justify-content-center' do |f| %>
    <div class="form-floating">
      <%= f.text_field :username, required: true, class: 'form-control',placeholder:'user.username'%>
      <%= f.label :username,t('user.username'),style:"margin-left: 10px"%>
    </div>
    <div class="form-floating">
      <%= f.password_field :password, required: true, class: 'form-control',placeholder:'Password'%>
      <%= f.label :password,t('user.password'),style:"margin-left: 10px"%>
    </div>
    <%= f.submit t('sign_in'), class:'col-4 btn btn-lg btn-primary'%>
  <% end %>
  <%= link_to t('register'), new_user_path %>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>F name</th>
      <th>S name</th>
      <th>Username</th>
      <th>Email</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.f_name %></td>
        <td><%= user.s_name %></td>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/show.html.erb
<div class="container">
  <div class="row" style="margin-bottom: 10px">
    <div class="col-10">
      <h3><%=t('page.user_head') %> <%= @user.username %></h3>
    </div>
    <div class="col-2">
      <%= button_to(t('change'), edit_user_path(@user), method: :get, class: "btn btn-outline-secondary btn-sm") %>
    </div>
  </div>
  <div class="row justify-content-end">
    <div class="col-4">
      <ul class="list-group">
        <li class="list-group-item"><label style="margin-right: 5px"><%=t('user.f_name') %> :</label><span><%= @user.f_name %></span></li>
        <li class="list-group-item"><label style="margin-right: 5px"><%=t('user.s_name') %> :</label><span><%= @user.s_name %></span>
        </li>
        <li class="list-group-item"><label style="margin-right: 5px"><%=t('user.username') %> :</label><span><%= @user.username %></span></li>
        <li class="list-group-item"><label style="margin-right: 5px"><%=t('user.email') %> :</label><span><%= @user.email %></span></li>
      </ul>
    </div>
    <div class="col-8">
      <% @user_recipes.each do |recipe| %>
        <div class="card mb-3">
          <div class="row g-0">
            <div class="col-md-4">
              <img src="<%= recipe[:image] %>" class="img-fluid rounded-start" alt="...">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <a href="/recipes/<%=recipe[:id] %>"><h4><%=recipe[:name]%></h4></a>
                <p class="card-text"><%= t('recipe.level') %>: <%=recipe[:level]%><br/>
                  <%= t('recipe.time') %>: <%= recipe[:time]%> мин</p>
                <p class="card-text"><small class="text-muted"><%=recipe[:username] %></small></p>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>